export const alphabet = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
];

export const initial = [
  { letter: 'a', typed: false },
  { letter: 'b', typed: false },
  { letter: 'c', typed: false },
  { letter: 'd', typed: false },
  { letter: 'e', typed: false },
  { letter: 'f', typed: false },
  { letter: 'g', typed: false },
  { letter: 'h', typed: false },
  { letter: 'i', typed: false },
  { letter: 'j', typed: false },
  { letter: 'k', typed: false },
  { letter: 'l', typed: false },
  { letter: 'm', typed: false },
  { letter: 'n', typed: false },
  { letter: 'o', typed: false },
  { letter: 'p', typed: false },
  { letter: 'q', typed: false },
  { letter: 'r', typed: false },
  { letter: 's', typed: false },
  { letter: 't', typed: false },
  { letter: 'u', typed: false },
  { letter: 'v', typed: false },
  { letter: 'w', typed: false },
  { letter: 'x', typed: false },
  { letter: 'y', typed: false },
  { letter: 'z', typed: false },
];
